rest_proxy:
  rest.proxy.url: http://localhost:8082

schema_registry:
  schema.registry.url: http://localhost:8081

kafi:
  auto.offset.reset: earliest
  enable.auto.commit: true
  fetch.min.bytes: -1
  consumer.request.timeout.ms: 1000
  consume.num.attempts: 1
